apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dash-api-dev
spec:
  replicas: 2
  selector:
  template:
    metadata:
      labels:
        run: dash-api-dev
    spec:
      containers:
        - image: hathbanger/dash-api:1
          name: dash-api
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1323
        - image: lou-bot
          name: lou-bot
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3030
        - image: mongo
          name: mongodb
          imagePullPolicy: IfNotPresent
          # ports:
          #   - containerPort: 27017
